### ISSUE TITLE
Can't get past connecting to WiFi

### ISSUE THREAD

**Issue by drpeppershaker** [MikeSchapp/BabyScout#11]
I really don't know what I'm doing wrong. But I got my wife all psyched to use this remote control and now I look like a dummy lol.

As far as I can tell, I have everything correctly loaded up onto the pico and I have `secrets.json` set up correctly. But I can't get it to connect to BabyBuddy.

Without the pico being connected to my laptop, I can't tell if the pico is doing anything, as Baby Buddy doesn't get updated when pressing keys. So I hooked up the pico to my laptop and loaded it up in Thonny.

I get the following error when trying to manually run `main.py` on the pico over Thonny:

```
﻿﻿Attempting to connect to **MY_SECRET_SSID**
WLAN Connected
Traceback (most recent call last):
  File "<stdin>", line 31, in <module>
  File "lib/scout.py", line 229, in connect_to_baby_buddy
  File "lib/scout.py", line 18, in __init__
  File "lib/scout.py", line 27, in init_children
KeyError: results
```

I have secrets.json set up as the following:

```
{
    "SSIDS_PASSWORD": {
        "**MY_SECRET_WIFI**": "**MY_SECRET_PASSWORD**"
    },
    "BASE_URL": "http://192.168.1.77:8000/api/",
    "AUTHORIZATION": {
        "CF-Access-Client-Id": "my cloudfront tunnel id",                #Note: This is unchanged
        "CF-Access-Client-Secret": "my cloudfront tunnel secret",  #Note: This is unchanged
        "Authorization": "**MY_SECRET_API**"
    }
}
```

Two caveats that may help debugging the issue:
My Wifi SSID contains a `:` and my wifi password contains a `#`. 

Really hope you see this before the baby comes! Thanks so much for any help you can spare.

**Comment by MikeSchapp** [comment]
Hey there @drpeppershaker  thanks for raising the issue!

Just so I have some background information, have you already added your child to BabyBuddy?

**Comment by drpeppershaker** [comment]
Yes, correct. Baby buddy is fully set up, and I've been adding test data for a week or so now.

**Comment by MikeSchapp** [comment]
@drpeppershaker I think I found the issue and will correct this in code but in the meantime for debugging can you add the word "Token" in front of your baby buddy api key?

So it will look like

{
    "SSIDS_PASSWORD": {
        "**MY_SECRET_WIFI**": "**MY_SECRET_PASSWORD**"
    },
    "BASE_URL": "http://192.168.1.77:8000/api/",
    "AUTHORIZATION": {
        "CF-Access-Client-Id": "my cloudfront tunnel id",                #Note: This is unchanged
        "CF-Access-Client-Secret": "my cloudfront tunnel secret",  #Note: This is unchanged
        "Authorization": "Token 12345"
    }
}

If that fixes it I will update this project to automatically insert the word Token.

**Comment by drpeppershaker** [comment]
Hey Mike,
I haven’t had a chance to test. Baby came early at 37 weeks!!!

I’m currently using one of the esp32 versions, but I’ll definitely give the fix a shot at some point because my ESP’s are super tall with the headers and dupont connectors. 
I have a much more slick 3D printed case for a pico version hanging around downstairs that I know we’re going to want to use eventually.

Cheers

**Comment by MikeSchapp** [comment]
Oh man! Had the same thing happen to me 36 weeks, 6 days. Hope you had the room assembled, I thought I had more time and had so much more to do! 

Congratulations, hope to hear from you when you have time but enjoy it!
