### ISSUE TITLE
Receving errors when trying to stop timers

### ISSUE THREAD

**Issue by element0355** [MikeSchapp/BabyScout#13]
When I try to stop any timers I get the error below. Can someone point into the right direction?

Error: active
Command failed to send, checking connection: 3
Lost connection, reconnecting...
Attempting to connect to NETWORK
Still attempting to connect to NETWORK
Still attempting to connect to NETWORK
WLAN Connected
Reconnected
Traceback (most recent call last):
  File "<stdin>", line 80, in <module>
  File "<stdin>", line 76, in button_pressed
  File "lib/utils.py", line 79, in __call__
  File "lib/scout.py", line 103, in sleep
  File "lib/scout.py", line 54, in resolve_timers
  File "lib/scout.py", line 91, in get_timer
KeyError: active

**Comment by element0355** [comment]
NVM, this was my fault no issues

**Comment by element0355** [comment]
Reopening because this is an issue. When trying to stop timers it crashes the program, and need to restart the pico

**Comment by MikeSchapp** [comment]
@element0355 Hey, thanks for reporting this issue. Let me look into it!

**Comment by MikeSchapp** [comment]
@element0355 what version of baby buddy are you using?

**Comment by MikeSchapp** [comment]
Created a branch to work on this, looks like the timer logic depends on a field that is no longer valid since 2.0. Did some testing and it seems to fix the issue. Will comment back when updates are merged.

**Comment by MikeSchapp** [comment]
@element0355 Merged, please try uploading the new firmware

**Comment by element0355** [comment]
@MikeSchapp thanks for looking into this currently in the hospital with my newborn will test it out when we are finally home and let you know!

**Comment by MikeSchapp** [comment]
@element0355 Oh man congratulations!!! Enjoy every moment of it!
